### ISSUE TITLE
List being used instead of string or buffer

### ISSUE THREAD

**Issue by teknix** [ncd-io/Industrial-Relay-Control#2]
> File "ncd-test.py", line 17, in <module>
>     print board1.turn_on_relay_by_index(1)
>   File "/home/pi/ncd-fusion-control/ncd_industrial_relay.py", line 21, in turn_on_relay_by_index
> 
>     return self.process_control_command_return(self.send_command(command, 4))
>   File "/home/pi/ncd-fusion-control/ncd_industrial_relay.py", line 122, in send_command
>     self.combus.send(command)
> TypeError: send() argument 1 must be string or buffer, not list
> 
> 

## ncd-test.py
````
# import the pyserial module
import socket
import ncd_industrial_relay as ncd


# set up your socket with the desired settings.
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
# instantiate the board object and pass it the network socket
board1 = ncd.Relay_Controller(sock)
# connect the socket using desired IP and Port
IP_ADDRESS = "192.168.1.101"
PORT = 2101
sock.connect((IP_ADDRESS, PORT))
sock.settimeout(.5)

# pass these methods a number between 1 and 512 to set the current status of the relay
print board1.turn_on_relay_by_index(1)
print board1.turn_on_relay_by_index(2)
print board1.turn_off_relay_by_index(1)
print board1.turn_off_relay_by_index(2)
```
## function in ncd_industrial_relay.py
```def send_command(self, command, bytes_back):
# 		The following line is causing problems and has been commented out until further study.
# 		command = self.convert_data(command)
		if self.combus_type == 'serial':
			self.combus.write(command)
			return self.combus.read(bytes_back)
		else:
			self.combus.send(command)
			return self.combus.recv(bytes_back)`


```

**Comment by kensley** [comment]
We have seen the same issue. We wrapped the `command` with bytearray in the send_command else statement for now.

**Comment by teknix** [comment]
So pretty much this:
`self.combus.send(byetarray(command))`
I will give this a shot, thank you :+1:

**Comment by teknix** [comment]
confirmed that using `bytearray()` for command in `self.combus.send()` is the fix
